// Code generated by counterfeiter. DO NOT EDIT.
package flyontimefakes

import (
	"context"
	"sync"

	"github.com/Bo0mer/flyontime/pkg/flyontime"
)

type FakeNotifier struct {
	NotifyStub        func(ctx context.Context, n *flyontime.Notification) error
	notifyMutex       sync.RWMutex
	notifyArgsForCall []struct {
		ctx context.Context
		n   *flyontime.Notification
	}
	notifyReturns struct {
		result1 error
	}
	notifyReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNotifier) Notify(ctx context.Context, n *flyontime.Notification) error {
	fake.notifyMutex.Lock()
	ret, specificReturn := fake.notifyReturnsOnCall[len(fake.notifyArgsForCall)]
	fake.notifyArgsForCall = append(fake.notifyArgsForCall, struct {
		ctx context.Context
		n   *flyontime.Notification
	}{ctx, n})
	fake.recordInvocation("Notify", []interface{}{ctx, n})
	fake.notifyMutex.Unlock()
	if fake.NotifyStub != nil {
		return fake.NotifyStub(ctx, n)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.notifyReturns.result1
}

func (fake *FakeNotifier) NotifyCallCount() int {
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	return len(fake.notifyArgsForCall)
}

func (fake *FakeNotifier) NotifyArgsForCall(i int) (context.Context, *flyontime.Notification) {
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	return fake.notifyArgsForCall[i].ctx, fake.notifyArgsForCall[i].n
}

func (fake *FakeNotifier) NotifyReturns(result1 error) {
	fake.NotifyStub = nil
	fake.notifyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNotifier) NotifyReturnsOnCall(i int, result1 error) {
	fake.NotifyStub = nil
	if fake.notifyReturnsOnCall == nil {
		fake.notifyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.notifyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNotifier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNotifier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ flyontime.Notifier = new(FakeNotifier)
